### PR TITLE
add h5 visualization

### PR DESCRIPTION
**Pull request by yangmuzhi**

### CODE REVIEW

**Comment by vsimko** [comment]
Thank you for your contribution @yangmuzhi, but we cannot accept a pull request until it passes travis CI build.

**Comment by yangmuzhi** [comment]
Thank you,@vsimko. I don not understand the travis CI build problem. It sounds like a linux problem? Anyway I will get over it. 
There are still some bugs in h5 version  function corrplotvis.  Here is a demo https://yangmuzhi.github.io/blogs/2018-10-17-corrplotVisdemo.html.

**Comment by vsimko** [comment]
The problem is as follows:
```
0.52schecking examples ... ERROR
Running examples in ‘corrplot-Ex.R’ failed
The error most likely occurred in:
> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: corrplotVis
> ### Title: This is an plot function for visualizing a correlation matrix by
> ###   using html5
> ### Aliases: corrplotVis
> 
> ### ** Examples
> 
> data(mtcars)
> M <- cor(mtcars)
> 
> corrplot::corrplotVis(M)
Error in yaml.load(readLines(con), error.label = error.label, ...) : 
  argument "error.label" is missing, with no default
Calls: <Anonymous> ... widget_dependencies -> getDependency -> <Anonymous> -> yaml.load
```

**Comment by vsimko** [comment]
The demo shown is impressive, especially how easy is to tweak the corrplot output. Well done!
However, the new functionality also introduces a lot of additional dependencies and extends the package beyond it original intent.

The idea behind corrplot, I think, is to have a small and flexible package that renders printable correlation plots that can be included into scientific papers.

I think it would be better to create a separate package for this interactive corrplot extension, e.g. `corrplot-vis` or `corrplot-shiny` that can be either used in shiny apps or to interactively tweak corrplot parameters.

By clicking a button, the tool could generate R code that represents the same parameterization when plotted using the standard corrplot (handy for automation).

Any opinion on this @taiyun ?

**Pull request closed without merging**
